// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Item = { id: string, name: string, image_url: string, desc: string, page_url: string, };
