// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Item = { name: string, image_url: string, status: string, page_url: string, };
