[package]
name = "retry"
version = "0.1.0"
edition = "2021"

[dependencies]
syn = { version = "2.0.96", features = ["full"] }
quote = "1.0"
proc-macro2 = "1.0"
tokio = { version = "1.0", features = ["time"] }

[lib]
proc-macro = true
